### ISSUE TITLE
the data is displayed as urlencoded in the app

### ISSUE THREAD

**Issue by lovasoa** [gbj/rust-ssr-sauron#1]
See : https://rust-ssr.herokuapp.com/Gérard

<img width="877" alt="Screenshot 2020-09-09 at 15 03 20" src="https://user-images.githubusercontent.com/552629/92601896-a897b500-f2ad-11ea-8187-03cb7a72073e.png">

**Comment by gbj** [comment]
Thanks, just committed a fix.
